### ISSUE TITLE
no headers installed

### ISSUE THREAD

**Issue by kemin711** [lballabio/dockerfiles#1]
I don't think this issue is related to your protocol.  When I build boost with this protocol, the headers are not installed: In regular boost install with default prefix, the boost is at
/usr/local/include/boost

Not sure someone knows where I did wrong.

**Comment by lballabio** [comment]
Dockerfiles build stuff as root by default, therefore the Boost headers are installed in `/usr/include/boost` and the libraries go to `/usr/lib`.

**Comment by kemin711** [comment]
I think I got it figured out somehow.  The problem was anaconda that is altering my environment.
Thanks for the reply.

**Comment by lballabio** [comment]
Ok, glad it worked out.
