### ISSUE TITLE
Putting up a python 3 docker?

### ISSUE THREAD

**Issue by adonoghuTcd** [lballabio/dockerfiles#2]
Is there any chance you could put up a python 3 version for Quantlib-python?

**Comment by lballabio** [comment]
I'm not using Python 3, so I'd have to research a bit and I'm a bit short on time.  You might try replacing the Ubuntu packages `python-dev` and `python` with the corresponding Python 3 packages in the Dockerfile for the `quantlib-python` image.  I'm not sure if `make` will pick up the Python executable; you might have to add `PYTHON=python3` to the `make` invocation for it to work.

**Comment by adonoghuTcd** [comment]
RUN apt-get update \
 && apt-get install -y python3 python3-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN cd /usr/bin \
	&& ln -s python3 python \
	&& ln -s python3-config python-config

above the code to get it to work with python3 but currently it only works with SWiG 1.8. 1.9 and 1.10 error. I have opened an issue on the SWIG repo.

**Comment by oddball** [comment]
@adonoghuTcd Do you have a link to the issue at the SWIG repo?
