### ISSUE TITLE
No manifest for quantlib-devenv

### ISSUE THREAD

**Issue by zeakdad** [lballabio/dockerfiles#4]
I'm sure I am doing something wrong, but I'm getting the following:

$ docker pull lballabio/quantlib-devenv
Using default tag: latest
Error response from daemon: manifest for lballabio/quantlib-devenv:latest not found: manifest unknown: manifest unknown

I have successfully pulled lballabio/quantlib-python3 and lballabio/quantlib.

**Comment by lballabio** [comment]
quantlib-devenv has no `latest`.  It has a few specific tags used for the Travis CI jobs (see <https://hub.docker.com/r/lballabio/quantlib-devenv/tags>).  You can pull one of those.
